#baseurl: /playbook/registrar
baseurl: /registrar-playbook

exclude: ['README.md']

sass:
 sass_dir: assets/css

permalink: pretty

#absolute: https://www.healthit.gov/playbook/registrar/
absolute: https://www.healthit.gov/registrar-playbook/